spring:
  application:
    name: demo-zuul # Spring 应用名
server:
  port: 28081 # 服务器端口。默认为 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


management:
  endpoints:
    # Actuator HTTP 配置项，对应 WebEndpointProperties 配置类
    web:
      base-path: /actuator # Actuator 提供的 API 接口的根目录spring:
  application:
    name: demo-zuul # Spring 应用名


#zuul:
#  ignoredPatterns: /**/actuator/**
#  routes:
#    consumer:
#      path: /consumer/**
#      serviceId: demo-consumer

kucoin:
  gray:
    custom:
      enabled: true