package cn.iocoder.springboot.lab36.prometheusdemo.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PositionDOExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public PositionDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table position
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSymbolIsNull() {
            addCriterion("symbol is null");
            return (Criteria) this;
        }

        public Criteria andSymbolIsNotNull() {
            addCriterion("symbol is not null");
            return (Criteria) this;
        }

        public Criteria andSymbolEqualTo(String value) {
            addCriterion("symbol =", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotEqualTo(String value) {
            addCriterion("symbol <>", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolGreaterThan(String value) {
            addCriterion("symbol >", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolGreaterThanOrEqualTo(String value) {
            addCriterion("symbol >=", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLessThan(String value) {
            addCriterion("symbol <", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLessThanOrEqualTo(String value) {
            addCriterion("symbol <=", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLike(String value) {
            addCriterion("symbol like", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotLike(String value) {
            addCriterion("symbol not like", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolIn(List<String> values) {
            addCriterion("symbol in", values, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotIn(List<String> values) {
            addCriterion("symbol not in", values, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolBetween(String value1, String value2) {
            addCriterion("symbol between", value1, value2, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotBetween(String value1, String value2) {
            addCriterion("symbol not between", value1, value2, "symbol");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRiskLimitIsNull() {
            addCriterion("risk_limit is null");
            return (Criteria) this;
        }

        public Criteria andRiskLimitIsNotNull() {
            addCriterion("risk_limit is not null");
            return (Criteria) this;
        }

        public Criteria andRiskLimitEqualTo(Integer value) {
            addCriterion("risk_limit =", value, "riskLimit");
            return (Criteria) this;
        }

        public Criteria andRiskLimitNotEqualTo(Integer value) {
            addCriterion("risk_limit <>", value, "riskLimit");
            return (Criteria) this;
        }

        public Criteria andRiskLimitGreaterThan(Integer value) {
            addCriterion("risk_limit >", value, "riskLimit");
            return (Criteria) this;
        }

        public Criteria andRiskLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("risk_limit >=", value, "riskLimit");
            return (Criteria) this;
        }

        public Criteria andRiskLimitLessThan(Integer value) {
            addCriterion("risk_limit <", value, "riskLimit");
            return (Criteria) this;
        }

        public Criteria andRiskLimitLessThanOrEqualTo(Integer value) {
            addCriterion("risk_limit <=", value, "riskLimit");
            return (Criteria) this;
        }

        public Criteria andRiskLimitIn(List<Integer> values) {
            addCriterion("risk_limit in", values, "riskLimit");
            return (Criteria) this;
        }

        public Criteria andRiskLimitNotIn(List<Integer> values) {
            addCriterion("risk_limit not in", values, "riskLimit");
            return (Criteria) this;
        }

        public Criteria andRiskLimitBetween(Integer value1, Integer value2) {
            addCriterion("risk_limit between", value1, value2, "riskLimit");
            return (Criteria) this;
        }

        public Criteria andRiskLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("risk_limit not between", value1, value2, "riskLimit");
            return (Criteria) this;
        }

        public Criteria andAutoDepositIsNull() {
            addCriterion("auto_deposit is null");
            return (Criteria) this;
        }

        public Criteria andAutoDepositIsNotNull() {
            addCriterion("auto_deposit is not null");
            return (Criteria) this;
        }

        public Criteria andAutoDepositEqualTo(Boolean value) {
            addCriterion("auto_deposit =", value, "autoDeposit");
            return (Criteria) this;
        }

        public Criteria andAutoDepositNotEqualTo(Boolean value) {
            addCriterion("auto_deposit <>", value, "autoDeposit");
            return (Criteria) this;
        }

        public Criteria andAutoDepositGreaterThan(Boolean value) {
            addCriterion("auto_deposit >", value, "autoDeposit");
            return (Criteria) this;
        }

        public Criteria andAutoDepositGreaterThanOrEqualTo(Boolean value) {
            addCriterion("auto_deposit >=", value, "autoDeposit");
            return (Criteria) this;
        }

        public Criteria andAutoDepositLessThan(Boolean value) {
            addCriterion("auto_deposit <", value, "autoDeposit");
            return (Criteria) this;
        }

        public Criteria andAutoDepositLessThanOrEqualTo(Boolean value) {
            addCriterion("auto_deposit <=", value, "autoDeposit");
            return (Criteria) this;
        }

        public Criteria andAutoDepositIn(List<Boolean> values) {
            addCriterion("auto_deposit in", values, "autoDeposit");
            return (Criteria) this;
        }

        public Criteria andAutoDepositNotIn(List<Boolean> values) {
            addCriterion("auto_deposit not in", values, "autoDeposit");
            return (Criteria) this;
        }

        public Criteria andAutoDepositBetween(Boolean value1, Boolean value2) {
            addCriterion("auto_deposit between", value1, value2, "autoDeposit");
            return (Criteria) this;
        }

        public Criteria andAutoDepositNotBetween(Boolean value1, Boolean value2) {
            addCriterion("auto_deposit not between", value1, value2, "autoDeposit");
            return (Criteria) this;
        }

        public Criteria andCrossModeIsNull() {
            addCriterion("margin_type is null");
            return (Criteria) this;
        }

        public Criteria andCrossModeIsNotNull() {
            addCriterion("margin_type is not null");
            return (Criteria) this;
        }

        public Criteria andCrossModeEqualTo(Integer value) {
            addCriterion("margin_type =", value, "marginType");
            return (Criteria) this;
        }

        public Criteria andCrossModeNotEqualTo(Integer value) {
            addCriterion("margin_type <>", value, "marginType");
            return (Criteria) this;
        }

        public Criteria andCrossModeGreaterThan(Integer value) {
            addCriterion("margin_type >", value, "marginType");
            return (Criteria) this;
        }

        public Criteria andCrossModeGreaterThanOrEqualTo(Integer value) {
            addCriterion("margin_type >=", value, "marginType");
            return (Criteria) this;
        }

        public Criteria andCrossModeLessThan(Integer value) {
            addCriterion("margin_type <", value, "marginType");
            return (Criteria) this;
        }

        public Criteria andCrossModeLessThanOrEqualTo(Integer value) {
            addCriterion("margin_type <=", value, "marginType");
            return (Criteria) this;
        }

        public Criteria andCrossModeIn(List<Integer> values) {
            addCriterion("margin_type in", values, "marginType");
            return (Criteria) this;
        }

        public Criteria andCrossModeNotIn(List<Integer> values) {
            addCriterion("margin_type not in", values, "marginType");
            return (Criteria) this;
        }

        public Criteria andCrossModeBetween(Integer value1, Integer value2) {
            addCriterion("margin_type between", value1, value2, "marginType");
            return (Criteria) this;
        }

        public Criteria andCrossModeNotBetween(Integer value1, Integer value2) {
            addCriterion("margin_type not between", value1, value2, "marginType");
            return (Criteria) this;
        }

        public Criteria andIsOpenIsNull() {
            addCriterion("is_open is null");
            return (Criteria) this;
        }

        public Criteria andIsOpenIsNotNull() {
            addCriterion("is_open is not null");
            return (Criteria) this;
        }

        public Criteria andIsOpenEqualTo(Boolean value) {
            addCriterion("is_open =", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotEqualTo(Boolean value) {
            addCriterion("is_open <>", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenGreaterThan(Boolean value) {
            addCriterion("is_open >", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_open >=", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenLessThan(Boolean value) {
            addCriterion("is_open <", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenLessThanOrEqualTo(Boolean value) {
            addCriterion("is_open <=", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenIn(List<Boolean> values) {
            addCriterion("is_open in", values, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotIn(List<Boolean> values) {
            addCriterion("is_open not in", values, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenBetween(Boolean value1, Boolean value2) {
            addCriterion("is_open between", value1, value2, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_open not between", value1, value2, "isOpen");
            return (Criteria) this;
        }

        public Criteria andAvgEntryPriceIsNull() {
            addCriterion("avg_entry_price is null");
            return (Criteria) this;
        }

        public Criteria andAvgEntryPriceIsNotNull() {
            addCriterion("avg_entry_price is not null");
            return (Criteria) this;
        }

        public Criteria andAvgEntryPriceEqualTo(BigDecimal value) {
            addCriterion("avg_entry_price =", value, "avgEntryPrice");
            return (Criteria) this;
        }

        public Criteria andAvgEntryPriceNotEqualTo(BigDecimal value) {
            addCriterion("avg_entry_price <>", value, "avgEntryPrice");
            return (Criteria) this;
        }

        public Criteria andAvgEntryPriceGreaterThan(BigDecimal value) {
            addCriterion("avg_entry_price >", value, "avgEntryPrice");
            return (Criteria) this;
        }

        public Criteria andAvgEntryPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("avg_entry_price >=", value, "avgEntryPrice");
            return (Criteria) this;
        }

        public Criteria andAvgEntryPriceLessThan(BigDecimal value) {
            addCriterion("avg_entry_price <", value, "avgEntryPrice");
            return (Criteria) this;
        }

        public Criteria andAvgEntryPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("avg_entry_price <=", value, "avgEntryPrice");
            return (Criteria) this;
        }

        public Criteria andAvgEntryPriceIn(List<BigDecimal> values) {
            addCriterion("avg_entry_price in", values, "avgEntryPrice");
            return (Criteria) this;
        }

        public Criteria andAvgEntryPriceNotIn(List<BigDecimal> values) {
            addCriterion("avg_entry_price not in", values, "avgEntryPrice");
            return (Criteria) this;
        }

        public Criteria andAvgEntryPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg_entry_price between", value1, value2, "avgEntryPrice");
            return (Criteria) this;
        }

        public Criteria andAvgEntryPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg_entry_price not between", value1, value2, "avgEntryPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentQtyIsNull() {
            addCriterion("current_qty is null");
            return (Criteria) this;
        }

        public Criteria andCurrentQtyIsNotNull() {
            addCriterion("current_qty is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentQtyEqualTo(Long value) {
            addCriterion("current_qty =", value, "currentQty");
            return (Criteria) this;
        }

        public Criteria andCurrentQtyNotEqualTo(Long value) {
            addCriterion("current_qty <>", value, "currentQty");
            return (Criteria) this;
        }

        public Criteria andCurrentQtyGreaterThan(Long value) {
            addCriterion("current_qty >", value, "currentQty");
            return (Criteria) this;
        }

        public Criteria andCurrentQtyGreaterThanOrEqualTo(Long value) {
            addCriterion("current_qty >=", value, "currentQty");
            return (Criteria) this;
        }

        public Criteria andCurrentQtyLessThan(Long value) {
            addCriterion("current_qty <", value, "currentQty");
            return (Criteria) this;
        }

        public Criteria andCurrentQtyLessThanOrEqualTo(Long value) {
            addCriterion("current_qty <=", value, "currentQty");
            return (Criteria) this;
        }

        public Criteria andCurrentQtyIn(List<Long> values) {
            addCriterion("current_qty in", values, "currentQty");
            return (Criteria) this;
        }

        public Criteria andCurrentQtyNotIn(List<Long> values) {
            addCriterion("current_qty not in", values, "currentQty");
            return (Criteria) this;
        }

        public Criteria andCurrentQtyBetween(Long value1, Long value2) {
            addCriterion("current_qty between", value1, value2, "currentQty");
            return (Criteria) this;
        }

        public Criteria andCurrentQtyNotBetween(Long value1, Long value2) {
            addCriterion("current_qty not between", value1, value2, "currentQty");
            return (Criteria) this;
        }

        public Criteria andCurrentCostIsNull() {
            addCriterion("current_cost is null");
            return (Criteria) this;
        }

        public Criteria andCurrentCostIsNotNull() {
            addCriterion("current_cost is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentCostEqualTo(BigDecimal value) {
            addCriterion("current_cost =", value, "currentCost");
            return (Criteria) this;
        }

        public Criteria andCurrentCostNotEqualTo(BigDecimal value) {
            addCriterion("current_cost <>", value, "currentCost");
            return (Criteria) this;
        }

        public Criteria andCurrentCostGreaterThan(BigDecimal value) {
            addCriterion("current_cost >", value, "currentCost");
            return (Criteria) this;
        }

        public Criteria andCurrentCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("current_cost >=", value, "currentCost");
            return (Criteria) this;
        }

        public Criteria andCurrentCostLessThan(BigDecimal value) {
            addCriterion("current_cost <", value, "currentCost");
            return (Criteria) this;
        }

        public Criteria andCurrentCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("current_cost <=", value, "currentCost");
            return (Criteria) this;
        }

        public Criteria andCurrentCostIn(List<BigDecimal> values) {
            addCriterion("current_cost in", values, "currentCost");
            return (Criteria) this;
        }

        public Criteria andCurrentCostNotIn(List<BigDecimal> values) {
            addCriterion("current_cost not in", values, "currentCost");
            return (Criteria) this;
        }

        public Criteria andCurrentCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_cost between", value1, value2, "currentCost");
            return (Criteria) this;
        }

        public Criteria andCurrentCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_cost not between", value1, value2, "currentCost");
            return (Criteria) this;
        }

        public Criteria andCurrentCommIsNull() {
            addCriterion("current_comm is null");
            return (Criteria) this;
        }

        public Criteria andCurrentCommIsNotNull() {
            addCriterion("current_comm is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentCommEqualTo(BigDecimal value) {
            addCriterion("current_comm =", value, "currentComm");
            return (Criteria) this;
        }

        public Criteria andCurrentCommNotEqualTo(BigDecimal value) {
            addCriterion("current_comm <>", value, "currentComm");
            return (Criteria) this;
        }

        public Criteria andCurrentCommGreaterThan(BigDecimal value) {
            addCriterion("current_comm >", value, "currentComm");
            return (Criteria) this;
        }

        public Criteria andCurrentCommGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("current_comm >=", value, "currentComm");
            return (Criteria) this;
        }

        public Criteria andCurrentCommLessThan(BigDecimal value) {
            addCriterion("current_comm <", value, "currentComm");
            return (Criteria) this;
        }

        public Criteria andCurrentCommLessThanOrEqualTo(BigDecimal value) {
            addCriterion("current_comm <=", value, "currentComm");
            return (Criteria) this;
        }

        public Criteria andCurrentCommIn(List<BigDecimal> values) {
            addCriterion("current_comm in", values, "currentComm");
            return (Criteria) this;
        }

        public Criteria andCurrentCommNotIn(List<BigDecimal> values) {
            addCriterion("current_comm not in", values, "currentComm");
            return (Criteria) this;
        }

        public Criteria andCurrentCommBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_comm between", value1, value2, "currentComm");
            return (Criteria) this;
        }

        public Criteria andCurrentCommNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_comm not between", value1, value2, "currentComm");
            return (Criteria) this;
        }

        public Criteria andUnrealisedCostIsNull() {
            addCriterion("unrealised_cost is null");
            return (Criteria) this;
        }

        public Criteria andUnrealisedCostIsNotNull() {
            addCriterion("unrealised_cost is not null");
            return (Criteria) this;
        }

        public Criteria andUnrealisedCostEqualTo(BigDecimal value) {
            addCriterion("unrealised_cost =", value, "unrealisedCost");
            return (Criteria) this;
        }

        public Criteria andUnrealisedCostNotEqualTo(BigDecimal value) {
            addCriterion("unrealised_cost <>", value, "unrealisedCost");
            return (Criteria) this;
        }

        public Criteria andUnrealisedCostGreaterThan(BigDecimal value) {
            addCriterion("unrealised_cost >", value, "unrealisedCost");
            return (Criteria) this;
        }

        public Criteria andUnrealisedCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("unrealised_cost >=", value, "unrealisedCost");
            return (Criteria) this;
        }

        public Criteria andUnrealisedCostLessThan(BigDecimal value) {
            addCriterion("unrealised_cost <", value, "unrealisedCost");
            return (Criteria) this;
        }

        public Criteria andUnrealisedCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("unrealised_cost <=", value, "unrealisedCost");
            return (Criteria) this;
        }

        public Criteria andUnrealisedCostIn(List<BigDecimal> values) {
            addCriterion("unrealised_cost in", values, "unrealisedCost");
            return (Criteria) this;
        }

        public Criteria andUnrealisedCostNotIn(List<BigDecimal> values) {
            addCriterion("unrealised_cost not in", values, "unrealisedCost");
            return (Criteria) this;
        }

        public Criteria andUnrealisedCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("unrealised_cost between", value1, value2, "unrealisedCost");
            return (Criteria) this;
        }

        public Criteria andUnrealisedCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("unrealised_cost not between", value1, value2, "unrealisedCost");
            return (Criteria) this;
        }

        public Criteria andPosCostIsNull() {
            addCriterion("pos_cost is null");
            return (Criteria) this;
        }

        public Criteria andPosCostIsNotNull() {
            addCriterion("pos_cost is not null");
            return (Criteria) this;
        }

        public Criteria andPosCostEqualTo(BigDecimal value) {
            addCriterion("pos_cost =", value, "posCost");
            return (Criteria) this;
        }

        public Criteria andPosCostNotEqualTo(BigDecimal value) {
            addCriterion("pos_cost <>", value, "posCost");
            return (Criteria) this;
        }

        public Criteria andPosCostGreaterThan(BigDecimal value) {
            addCriterion("pos_cost >", value, "posCost");
            return (Criteria) this;
        }

        public Criteria andPosCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_cost >=", value, "posCost");
            return (Criteria) this;
        }

        public Criteria andPosCostLessThan(BigDecimal value) {
            addCriterion("pos_cost <", value, "posCost");
            return (Criteria) this;
        }

        public Criteria andPosCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_cost <=", value, "posCost");
            return (Criteria) this;
        }

        public Criteria andPosCostIn(List<BigDecimal> values) {
            addCriterion("pos_cost in", values, "posCost");
            return (Criteria) this;
        }

        public Criteria andPosCostNotIn(List<BigDecimal> values) {
            addCriterion("pos_cost not in", values, "posCost");
            return (Criteria) this;
        }

        public Criteria andPosCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_cost between", value1, value2, "posCost");
            return (Criteria) this;
        }

        public Criteria andPosCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_cost not between", value1, value2, "posCost");
            return (Criteria) this;
        }

        public Criteria andPosCrossMarginIsNull() {
            addCriterion("pos_cross_margin is null");
            return (Criteria) this;
        }

        public Criteria andPosCrossMarginIsNotNull() {
            addCriterion("pos_cross_margin is not null");
            return (Criteria) this;
        }

        public Criteria andPosCrossMarginEqualTo(BigDecimal value) {
            addCriterion("pos_cross_margin =", value, "posCrossMargin");
            return (Criteria) this;
        }

        public Criteria andPosCrossMarginNotEqualTo(BigDecimal value) {
            addCriterion("pos_cross_margin <>", value, "posCrossMargin");
            return (Criteria) this;
        }

        public Criteria andPosCrossMarginGreaterThan(BigDecimal value) {
            addCriterion("pos_cross_margin >", value, "posCrossMargin");
            return (Criteria) this;
        }

        public Criteria andPosCrossMarginGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_cross_margin >=", value, "posCrossMargin");
            return (Criteria) this;
        }

        public Criteria andPosCrossMarginLessThan(BigDecimal value) {
            addCriterion("pos_cross_margin <", value, "posCrossMargin");
            return (Criteria) this;
        }

        public Criteria andPosCrossMarginLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_cross_margin <=", value, "posCrossMargin");
            return (Criteria) this;
        }

        public Criteria andPosCrossMarginIn(List<BigDecimal> values) {
            addCriterion("pos_cross_margin in", values, "posCrossMargin");
            return (Criteria) this;
        }

        public Criteria andPosCrossMarginNotIn(List<BigDecimal> values) {
            addCriterion("pos_cross_margin not in", values, "posCrossMargin");
            return (Criteria) this;
        }

        public Criteria andPosCrossMarginBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_cross_margin between", value1, value2, "posCrossMargin");
            return (Criteria) this;
        }

        public Criteria andPosCrossMarginNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_cross_margin not between", value1, value2, "posCrossMargin");
            return (Criteria) this;
        }

        public Criteria andPosInitIsNull() {
            addCriterion("pos_init is null");
            return (Criteria) this;
        }

        public Criteria andPosInitIsNotNull() {
            addCriterion("pos_init is not null");
            return (Criteria) this;
        }

        public Criteria andPosInitEqualTo(BigDecimal value) {
            addCriterion("pos_init =", value, "posInit");
            return (Criteria) this;
        }

        public Criteria andPosInitNotEqualTo(BigDecimal value) {
            addCriterion("pos_init <>", value, "posInit");
            return (Criteria) this;
        }

        public Criteria andPosInitGreaterThan(BigDecimal value) {
            addCriterion("pos_init >", value, "posInit");
            return (Criteria) this;
        }

        public Criteria andPosInitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_init >=", value, "posInit");
            return (Criteria) this;
        }

        public Criteria andPosInitLessThan(BigDecimal value) {
            addCriterion("pos_init <", value, "posInit");
            return (Criteria) this;
        }

        public Criteria andPosInitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_init <=", value, "posInit");
            return (Criteria) this;
        }

        public Criteria andPosInitIn(List<BigDecimal> values) {
            addCriterion("pos_init in", values, "posInit");
            return (Criteria) this;
        }

        public Criteria andPosInitNotIn(List<BigDecimal> values) {
            addCriterion("pos_init not in", values, "posInit");
            return (Criteria) this;
        }

        public Criteria andPosInitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_init between", value1, value2, "posInit");
            return (Criteria) this;
        }

        public Criteria andPosInitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_init not between", value1, value2, "posInit");
            return (Criteria) this;
        }

        public Criteria andPosCommCommonIsNull() {
            addCriterion("pos_comm_common is null");
            return (Criteria) this;
        }

        public Criteria andPosCommCommonIsNotNull() {
            addCriterion("pos_comm_common is not null");
            return (Criteria) this;
        }

        public Criteria andPosCommCommonEqualTo(BigDecimal value) {
            addCriterion("pos_comm_common =", value, "posCommCommon");
            return (Criteria) this;
        }

        public Criteria andPosCommCommonNotEqualTo(BigDecimal value) {
            addCriterion("pos_comm_common <>", value, "posCommCommon");
            return (Criteria) this;
        }

        public Criteria andPosCommCommonGreaterThan(BigDecimal value) {
            addCriterion("pos_comm_common >", value, "posCommCommon");
            return (Criteria) this;
        }

        public Criteria andPosCommCommonGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_comm_common >=", value, "posCommCommon");
            return (Criteria) this;
        }

        public Criteria andPosCommCommonLessThan(BigDecimal value) {
            addCriterion("pos_comm_common <", value, "posCommCommon");
            return (Criteria) this;
        }

        public Criteria andPosCommCommonLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_comm_common <=", value, "posCommCommon");
            return (Criteria) this;
        }

        public Criteria andPosCommCommonIn(List<BigDecimal> values) {
            addCriterion("pos_comm_common in", values, "posCommCommon");
            return (Criteria) this;
        }

        public Criteria andPosCommCommonNotIn(List<BigDecimal> values) {
            addCriterion("pos_comm_common not in", values, "posCommCommon");
            return (Criteria) this;
        }

        public Criteria andPosCommCommonBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_comm_common between", value1, value2, "posCommCommon");
            return (Criteria) this;
        }

        public Criteria andPosCommCommonNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_comm_common not between", value1, value2, "posCommCommon");
            return (Criteria) this;
        }

        public Criteria andPosCommFundingIsNull() {
            addCriterion("pos_comm_funding is null");
            return (Criteria) this;
        }

        public Criteria andPosCommFundingIsNotNull() {
            addCriterion("pos_comm_funding is not null");
            return (Criteria) this;
        }

        public Criteria andPosCommFundingEqualTo(BigDecimal value) {
            addCriterion("pos_comm_funding =", value, "posCommFunding");
            return (Criteria) this;
        }

        public Criteria andPosCommFundingNotEqualTo(BigDecimal value) {
            addCriterion("pos_comm_funding <>", value, "posCommFunding");
            return (Criteria) this;
        }

        public Criteria andPosCommFundingGreaterThan(BigDecimal value) {
            addCriterion("pos_comm_funding >", value, "posCommFunding");
            return (Criteria) this;
        }

        public Criteria andPosCommFundingGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_comm_funding >=", value, "posCommFunding");
            return (Criteria) this;
        }

        public Criteria andPosCommFundingLessThan(BigDecimal value) {
            addCriterion("pos_comm_funding <", value, "posCommFunding");
            return (Criteria) this;
        }

        public Criteria andPosCommFundingLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_comm_funding <=", value, "posCommFunding");
            return (Criteria) this;
        }

        public Criteria andPosCommFundingIn(List<BigDecimal> values) {
            addCriterion("pos_comm_funding in", values, "posCommFunding");
            return (Criteria) this;
        }

        public Criteria andPosCommFundingNotIn(List<BigDecimal> values) {
            addCriterion("pos_comm_funding not in", values, "posCommFunding");
            return (Criteria) this;
        }

        public Criteria andPosCommFundingBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_comm_funding between", value1, value2, "posCommFunding");
            return (Criteria) this;
        }

        public Criteria andPosCommFundingNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_comm_funding not between", value1, value2, "posCommFunding");
            return (Criteria) this;
        }

        public Criteria andPosLossIsNull() {
            addCriterion("pos_loss is null");
            return (Criteria) this;
        }

        public Criteria andPosLossIsNotNull() {
            addCriterion("pos_loss is not null");
            return (Criteria) this;
        }

        public Criteria andPosLossEqualTo(BigDecimal value) {
            addCriterion("pos_loss =", value, "posLoss");
            return (Criteria) this;
        }

        public Criteria andPosLossNotEqualTo(BigDecimal value) {
            addCriterion("pos_loss <>", value, "posLoss");
            return (Criteria) this;
        }

        public Criteria andPosLossGreaterThan(BigDecimal value) {
            addCriterion("pos_loss >", value, "posLoss");
            return (Criteria) this;
        }

        public Criteria andPosLossGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_loss >=", value, "posLoss");
            return (Criteria) this;
        }

        public Criteria andPosLossLessThan(BigDecimal value) {
            addCriterion("pos_loss <", value, "posLoss");
            return (Criteria) this;
        }

        public Criteria andPosLossLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_loss <=", value, "posLoss");
            return (Criteria) this;
        }

        public Criteria andPosLossIn(List<BigDecimal> values) {
            addCriterion("pos_loss in", values, "posLoss");
            return (Criteria) this;
        }

        public Criteria andPosLossNotIn(List<BigDecimal> values) {
            addCriterion("pos_loss not in", values, "posLoss");
            return (Criteria) this;
        }

        public Criteria andPosLossBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_loss between", value1, value2, "posLoss");
            return (Criteria) this;
        }

        public Criteria andPosLossNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_loss not between", value1, value2, "posLoss");
            return (Criteria) this;
        }

        public Criteria andPosProfitIsNull() {
            addCriterion("pos_profit is null");
            return (Criteria) this;
        }

        public Criteria andPosProfitIsNotNull() {
            addCriterion("pos_profit is not null");
            return (Criteria) this;
        }

        public Criteria andPosProfitEqualTo(BigDecimal value) {
            addCriterion("pos_profit =", value, "posProfit");
            return (Criteria) this;
        }

        public Criteria andPosProfitNotEqualTo(BigDecimal value) {
            addCriterion("pos_profit <>", value, "posProfit");
            return (Criteria) this;
        }

        public Criteria andPosProfitGreaterThan(BigDecimal value) {
            addCriterion("pos_profit >", value, "posProfit");
            return (Criteria) this;
        }

        public Criteria andPosProfitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_profit >=", value, "posProfit");
            return (Criteria) this;
        }

        public Criteria andPosProfitLessThan(BigDecimal value) {
            addCriterion("pos_profit <", value, "posProfit");
            return (Criteria) this;
        }

        public Criteria andPosProfitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_profit <=", value, "posProfit");
            return (Criteria) this;
        }

        public Criteria andPosProfitIn(List<BigDecimal> values) {
            addCriterion("pos_profit in", values, "posProfit");
            return (Criteria) this;
        }

        public Criteria andPosProfitNotIn(List<BigDecimal> values) {
            addCriterion("pos_profit not in", values, "posProfit");
            return (Criteria) this;
        }

        public Criteria andPosProfitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_profit between", value1, value2, "posProfit");
            return (Criteria) this;
        }

        public Criteria andPosProfitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_profit not between", value1, value2, "posProfit");
            return (Criteria) this;
        }

        public Criteria andPosMaintIsNull() {
            addCriterion("pos_maint is null");
            return (Criteria) this;
        }

        public Criteria andPosMaintIsNotNull() {
            addCriterion("pos_maint is not null");
            return (Criteria) this;
        }

        public Criteria andPosMaintEqualTo(BigDecimal value) {
            addCriterion("pos_maint =", value, "posMaint");
            return (Criteria) this;
        }

        public Criteria andPosMaintNotEqualTo(BigDecimal value) {
            addCriterion("pos_maint <>", value, "posMaint");
            return (Criteria) this;
        }

        public Criteria andPosMaintGreaterThan(BigDecimal value) {
            addCriterion("pos_maint >", value, "posMaint");
            return (Criteria) this;
        }

        public Criteria andPosMaintGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_maint >=", value, "posMaint");
            return (Criteria) this;
        }

        public Criteria andPosMaintLessThan(BigDecimal value) {
            addCriterion("pos_maint <", value, "posMaint");
            return (Criteria) this;
        }

        public Criteria andPosMaintLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pos_maint <=", value, "posMaint");
            return (Criteria) this;
        }

        public Criteria andPosMaintIn(List<BigDecimal> values) {
            addCriterion("pos_maint in", values, "posMaint");
            return (Criteria) this;
        }

        public Criteria andPosMaintNotIn(List<BigDecimal> values) {
            addCriterion("pos_maint not in", values, "posMaint");
            return (Criteria) this;
        }

        public Criteria andPosMaintBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_maint between", value1, value2, "posMaint");
            return (Criteria) this;
        }

        public Criteria andPosMaintNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pos_maint not between", value1, value2, "posMaint");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceIsNull() {
            addCriterion("liquidation_price is null");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceIsNotNull() {
            addCriterion("liquidation_price is not null");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceEqualTo(BigDecimal value) {
            addCriterion("liquidation_price =", value, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceNotEqualTo(BigDecimal value) {
            addCriterion("liquidation_price <>", value, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceGreaterThan(BigDecimal value) {
            addCriterion("liquidation_price >", value, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("liquidation_price >=", value, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceLessThan(BigDecimal value) {
            addCriterion("liquidation_price <", value, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("liquidation_price <=", value, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceIn(List<BigDecimal> values) {
            addCriterion("liquidation_price in", values, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceNotIn(List<BigDecimal> values) {
            addCriterion("liquidation_price not in", values, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("liquidation_price between", value1, value2, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("liquidation_price not between", value1, value2, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andBankruptPriceIsNull() {
            addCriterion("bankrupt_price is null");
            return (Criteria) this;
        }

        public Criteria andBankruptPriceIsNotNull() {
            addCriterion("bankrupt_price is not null");
            return (Criteria) this;
        }

        public Criteria andBankruptPriceEqualTo(BigDecimal value) {
            addCriterion("bankrupt_price =", value, "bankruptPrice");
            return (Criteria) this;
        }

        public Criteria andBankruptPriceNotEqualTo(BigDecimal value) {
            addCriterion("bankrupt_price <>", value, "bankruptPrice");
            return (Criteria) this;
        }

        public Criteria andBankruptPriceGreaterThan(BigDecimal value) {
            addCriterion("bankrupt_price >", value, "bankruptPrice");
            return (Criteria) this;
        }

        public Criteria andBankruptPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bankrupt_price >=", value, "bankruptPrice");
            return (Criteria) this;
        }

        public Criteria andBankruptPriceLessThan(BigDecimal value) {
            addCriterion("bankrupt_price <", value, "bankruptPrice");
            return (Criteria) this;
        }

        public Criteria andBankruptPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bankrupt_price <=", value, "bankruptPrice");
            return (Criteria) this;
        }

        public Criteria andBankruptPriceIn(List<BigDecimal> values) {
            addCriterion("bankrupt_price in", values, "bankruptPrice");
            return (Criteria) this;
        }

        public Criteria andBankruptPriceNotIn(List<BigDecimal> values) {
            addCriterion("bankrupt_price not in", values, "bankruptPrice");
            return (Criteria) this;
        }

        public Criteria andBankruptPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bankrupt_price between", value1, value2, "bankruptPrice");
            return (Criteria) this;
        }

        public Criteria andBankruptPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bankrupt_price not between", value1, value2, "bankruptPrice");
            return (Criteria) this;
        }

        public Criteria andOpeningTimestampIsNull() {
            addCriterion("opening_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andOpeningTimestampIsNotNull() {
            addCriterion("opening_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andOpeningTimestampEqualTo(Long value) {
            addCriterion("opening_timestamp =", value, "openingTimestamp");
            return (Criteria) this;
        }

        public Criteria andOpeningTimestampNotEqualTo(Long value) {
            addCriterion("opening_timestamp <>", value, "openingTimestamp");
            return (Criteria) this;
        }

        public Criteria andOpeningTimestampGreaterThan(Long value) {
            addCriterion("opening_timestamp >", value, "openingTimestamp");
            return (Criteria) this;
        }

        public Criteria andOpeningTimestampGreaterThanOrEqualTo(Long value) {
            addCriterion("opening_timestamp >=", value, "openingTimestamp");
            return (Criteria) this;
        }

        public Criteria andOpeningTimestampLessThan(Long value) {
            addCriterion("opening_timestamp <", value, "openingTimestamp");
            return (Criteria) this;
        }

        public Criteria andOpeningTimestampLessThanOrEqualTo(Long value) {
            addCriterion("opening_timestamp <=", value, "openingTimestamp");
            return (Criteria) this;
        }

        public Criteria andOpeningTimestampIn(List<Long> values) {
            addCriterion("opening_timestamp in", values, "openingTimestamp");
            return (Criteria) this;
        }

        public Criteria andOpeningTimestampNotIn(List<Long> values) {
            addCriterion("opening_timestamp not in", values, "openingTimestamp");
            return (Criteria) this;
        }

        public Criteria andOpeningTimestampBetween(Long value1, Long value2) {
            addCriterion("opening_timestamp between", value1, value2, "openingTimestamp");
            return (Criteria) this;
        }

        public Criteria andOpeningTimestampNotBetween(Long value1, Long value2) {
            addCriterion("opening_timestamp not between", value1, value2, "openingTimestamp");
            return (Criteria) this;
        }

        public Criteria andSnapshotIdIsNull() {
            addCriterion("snapshot_id is null");
            return (Criteria) this;
        }

        public Criteria andSnapshotIdIsNotNull() {
            addCriterion("snapshot_id is not null");
            return (Criteria) this;
        }

        public Criteria andSnapshotIdEqualTo(Long value) {
            addCriterion("snapshot_id =", value, "snapshotId");
            return (Criteria) this;
        }

        public Criteria andSnapshotIdNotEqualTo(Long value) {
            addCriterion("snapshot_id <>", value, "snapshotId");
            return (Criteria) this;
        }

        public Criteria andSnapshotIdGreaterThan(Long value) {
            addCriterion("snapshot_id >", value, "snapshotId");
            return (Criteria) this;
        }

        public Criteria andSnapshotIdGreaterThanOrEqualTo(Long value) {
            addCriterion("snapshot_id >=", value, "snapshotId");
            return (Criteria) this;
        }

        public Criteria andSnapshotIdLessThan(Long value) {
            addCriterion("snapshot_id <", value, "snapshotId");
            return (Criteria) this;
        }

        public Criteria andSnapshotIdLessThanOrEqualTo(Long value) {
            addCriterion("snapshot_id <=", value, "snapshotId");
            return (Criteria) this;
        }

        public Criteria andSnapshotIdIn(List<Long> values) {
            addCriterion("snapshot_id in", values, "snapshotId");
            return (Criteria) this;
        }

        public Criteria andSnapshotIdNotIn(List<Long> values) {
            addCriterion("snapshot_id not in", values, "snapshotId");
            return (Criteria) this;
        }

        public Criteria andSnapshotIdBetween(Long value1, Long value2) {
            addCriterion("snapshot_id between", value1, value2, "snapshotId");
            return (Criteria) this;
        }

        public Criteria andSnapshotIdNotBetween(Long value1, Long value2) {
            addCriterion("snapshot_id not between", value1, value2, "snapshotId");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table position
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table position
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}