spring:
  application:
    name: demo-provider # Spring 应用名

server:
  port: 18080 # 服务器端口。默认为 8080



eureka:
  client:
    register-with-eureka: true # 注册到 Eureka-Server，默认为 true
    fetch-registry: true # 从 Eureka-Server 获取注册表，默认为 true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ # Eureka-Server 地址
  instance:
   metadata-map:
    route: btc

kucoin:
  gray:
    custom:
      enabled: true


feign:
  hystrix:
    #开启feign的hystrix支持,默认是false
    enabled: true